# Generated by Django 5.1.1 on 2024-09-27 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Habit', max_length=40)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
